name: Build DFRoot

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c

      - name: Install LLVM tools
        run: sudo apt-get install -y llvm

      - name: Build LKM
        run: |
          chmod +x dirtyfrag-lkm/build.sh
          cd dirtyfrag-lkm
          docker run -v "$(pwd)":/src -w /src \
            --user "$(id -u)" \
            ghcr.io/ylarod/ddk-min:android15-6.6 \
            make
          cp dirtyfrag.ko dirtyfrag-android15-6.6.ko
          llvm-objcopy --strip-unneeded \
            -R .comment -R .note.gnu.build-id \
            -R .BTF -R .BTF.base -R .llvm_addrsig \
            dirtyfrag-android15-6.6.ko
          mkdir -p ../app/src/main/jni/ko
          cp dirtyfrag-android15-6.6.ko \
            ../app/src/main/jni/ko/

      # 1. Zostavenie surového APK aplikácie
      - name: Build APK (Release Mode)
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease

      # 2. Oficiálne podpísanie vygenerovaného APK pomocou vašich Secrets
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_STORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0" # Týmto prinútime akciu použiť dostupnú verziu nástrojov

      # 3. Automatické vytvorenie GitHub Release (Zoberie už podpísané APK)
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v2.1-${{ github.run_number }}
          name: DFRoot Release v2.1 (Build #${{ github.run_number }})
          body: |
            Automaticky vygenerovaná, podpísaná a optimalizovaná stabilná verzia aplikácie DFRoot.
            - Zraniteľnosť: DIRTYFRAG
          files: ${{ steps.sign_app.outputs.signedReleaseFile }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
